package co.edu.unicauca.UsuariosMicroService.repository;

import co.edu.unicauca.UsuariosMicroService.infra.dto.UsuarioRequest;
import co.edu.unicauca.UsuariosMicroService.service.UsuarioService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.CommandLineRunner;
import org.springframework.stereotype.Component;

@Component
@org.springframework.core.annotation.Order(1)
public class DataLoader implements CommandLineRunner {
    @Autowired
    private UsuarioService usuarioService;
    @Autowired
    private UsuarioRepository repository;

    @Override
    public void run(String... args) throws Exception {
        System.out.println("CARGANDO DATOS DE USUARIOS");
        // Do not delete existing users — deletion caused foreign key constraint errors
        // only insert initial records when there are no users in the repository
        if (repository.count() == 0) {

            UsuarioRequest admin = new UsuarioRequest();
            // id will be generated by the database
            admin.setNombre("jefe");
            admin.setContrasenia("admin123");
            admin.setTelefono("3150001111");
            admin.setRol("administrador");
            admin.setEstado(true);
            try { usuarioService.save(admin); } catch (Exception e) { System.err.println("Skipping initial admin: " + e.getMessage()); }

            UsuarioRequest user1 = new UsuarioRequest();
            // id will be generated by the database
            user1.setNombre("jesus");
            user1.setContrasenia("admin123");
            user1.setTelefono("3156890634");
            user1.setRol("barbero");
            user1.setEstado(true);
            try { usuarioService.save(user1); } catch (Exception e) { System.err.println("Skipping initial user1: " + e.getMessage()); }

            UsuarioRequest user2 = new UsuarioRequest();
            // id will be generated by the database
            user2.setNombre("carlos");
            user2.setContrasenia("0002");
            user2.setTelefono("3152223344");
            user2.setRol("barbero");
            user2.setEstado(true);
            try { usuarioService.save(user2); } catch (Exception e) { System.err.println("Skipping initial user2: " + e.getMessage()); }

            UsuarioRequest user3 = new UsuarioRequest();
            // id will be generated by the database
            user3.setNombre("juan");
            user3.setContrasenia("1111");
            user3.setTelefono("3154445566");
            user3.setRol("cliente");
            user3.setEstado(true);
            try { usuarioService.save(user3); } catch (Exception e) { System.err.println("Skipping initial user3: " + e.getMessage()); }

            UsuarioRequest user4 = new UsuarioRequest();
            // id will be generated by the database
            user4.setNombre("mateo");
            user4.setContrasenia("2222");
            user4.setTelefono("3157778899");
            user4.setRol("cliente");
            user4.setEstado(true);
            try { usuarioService.save(user4); } catch (Exception e) { System.err.println("Skipping initial user4: " + e.getMessage()); }

            UsuarioRequest user5 = new UsuarioRequest();
            // id will be generated by the database
            user5.setNombre("andres");
            user5.setContrasenia("3333");
            user5.setTelefono("3161234567");
            user5.setRol("cliente");
            user5.setEstado(true);
            try { usuarioService.save(user5); } catch (Exception e) { System.err.println("Skipping initial user5: " + e.getMessage()); }

            UsuarioRequest user6 = new UsuarioRequest();
            // id will be generated by the database
            user6.setNombre("felipe");
            user6.setContrasenia("4444");
            user6.setTelefono("3169876543");
            user6.setRol("cliente");
            user6.setEstado(true);
            try { usuarioService.save(user6); } catch (Exception e) { System.err.println("Skipping initial user6: " + e.getMessage()); }

            System.out.println("Usuarios iniciales cargados.");
        }
    }

}
